# IMEC2001 Herramientas Computacionales
## Actividad Clase 9: Sistemas de Ecuaciones
### Fecha Límite Entrega (Bloque Neón): <font color="#FF5733">23.59h de Septiembre 6, 2023</font>

Universidad de los Andes — Septiembre 4, 2023.

___
### Tener en Cuenta
La entrega de la **Actividad Clase 9** se puede realizar de dos maneras:
1. Enviar vía Bloque Neón el archivo en Jupyter Notebook (extensión '.ipynb').
2. Enviar vía Bloque Neón el archivo PDF del Jupyter Notebook.

**Nota:** <font color="#FF5733">El nombre del archivo debe ser: `AC9_NombreApellido.ipynb`.</font>

---

## TABLA DE CONTENIDO

### Sección 1: Ejercicios [→](#section1)
1. Ejercicio 1: Ecuaciones Lineales [→](#exercise1)
2. Ejercicio 2: Ecuaciones No Lineales [→](#exercise2)
___

In [17]:
import numpy as np
import sympy as sym
import scipy

<a id="section1"></a>
# Sección 1: Ejercicios

<a id="exercise1"></a>
## Ejercicio 1: Ecuaciones Lineales

Se tiene el siguiente sistema de ecuaciones lineales:

$$
\begin{cases}
  3x_1 + 2x_2 + x_3 = 1 \\
  \\
  2x_1 + 2x_2 + 4x_3 = -2 \\
  \\
  -x_1 + \frac{1}{2}x_2 - x_3 = 0
\end{cases}
$$

<div class="alert alert-block alert-warning">

1. Utilizando la librería `numpy.linalg.inv` y `numpy.dots`, resuelva el sistema de ecuaciones.
2. Utilizando la librería `numpy.linalg.solve`, resuelva el sistema de ecuaciones.
3. Utilizando la librería `sympy.rref()`, resuelva el sistema de ecuaciones.
4. Utilizando la librería `scipy.optimize.fsolve`, resuelva el sistema de ecuaciones.
5. Utilizando la librería `sympy.solve`, resuelva el sistema de ecuaciones.
    
</div>

In [9]:
A_np = np.array([[3,2,1],
              [2,2,4],
              [-1,1/2,-1]])
b_np = np.array([1,-2,0])

In [10]:
# Ítem 1
np.dot(np.linalg.inv(A_np),b_np)

array([ 0.69230769, -0.15384615, -0.76923077])

In [11]:
# Ítem 2
np.linalg.solve(A_np,b_np)

array([ 0.69230769, -0.15384615, -0.76923077])

In [15]:
# Ítem 3
A_sym = sym.Matrix([[3,2,1,1],
              [2,2,4,-2],
              [-1,1/2,-1,0]])

A_sym.rref()[0]

Matrix([
[1, 0, 0,  0.692307692307692],
[0, 1, 0, -0.153846153846154],
[0, 0, 1, -0.769230769230769]])

In [28]:
# Ítem 4
def f2(z):
    ## Definimos las incógnitas
    x1 = z[0]
    x2 = z[1]
    x3 = z[2]

    ## Creamos una lista vacía para alojar las funciones
    F = np.zeros(3)

    ## Alojamos las funciones en F (noten la parte derecha igual a cero)
    F[0] = 3*x1 + 2*x2 + x3 - 1
    F[1] = 2*x1 + 2*x2 + 4*x3 + 2
    F[2] = -x1 + 0.5*x2 -x3

    return F

estimacion = [1,0,-1]

scipy.optimize.fsolve(func=f2,x0=estimacion)

array([ 0.69230769, -0.15384615, -0.76923077])

In [24]:
# Ítem 5
x1,x2,x3 = sym.symbols("x1,x2,x3",real=True)
sym.solve([3*x1 + 2*x2 + x3 - 1, 2*x1 + 2*x2 + 4*x3 + 2, -x1 + 0.5*x2 -x3],[x1,x2,x3])


{x1: 0.692307692307692, x2: -0.153846153846154, x3: -0.769230769230769}

<a id='exercise2'></a>
## Ejercicio 2: Ecuaciones No Lineales

Se tiene el siguiente sistema de ecuaciones no lineales:

$$
\begin{cases}
  x^2 + y^2 = 1 \\
  \\
  xy + yz = -1.1 \\
  \\
  y^2 + z^2 = 2
\end{cases}
$$

<div class="alert alert-block alert-warning">

1. Utilizando la librería `scipy.optimize.fsolve`, resuelva el sistema de ecuaciones.
1. Utilizando la librería `scipy.optimize.roots`, resuelva el sistema de ecuaciones.
3. Utilizando la librería `sympy.solve`, resuelva el sistema de ecuaciones.
    
</div>

In [35]:
# Ítem 1
def f2(z):
    ## Definimos las incógnitas
    x1 = z[0]
    x2 = z[1]
    x3 = z[2]

    ## Creamos una lista vacía para alojar las funciones
    F = np.zeros(3)

    ## Alojamos las funciones en F (noten la parte derecha igual a cero)
    F[0] = x1**2 + x2**2 -1
    F[1] = x1*x2 + x2*x3 +1.1
    F[2] = x2**2 + x3**2 -2

    return F

estimacion2 = [1,1,1]

scipy.optimize.fsolve(func=f2,x0=estimacion2)

array([ 0.10056089, -0.99493091,  1.00504353])

In [37]:
# Ítem 2
scipy.optimize.root(fun=f2, x0=estimacion2).x

array([ 0.10056089, -0.99493091,  1.00504353])

In [30]:
# Ítem 3
sym.solve([x1**2 + x2**2 -1, x1*x2 + x2*x3 +1.1, x2**2 + x3**2 -2],[x1,x2,x3])

[(-0.864139354188464, 0.503252597154495, -1.32164171523800),
 (-0.100560885095735, 0.994930906339110, -1.00504352722220),
 (0.100560885095735, -0.994930906339110, 1.00504352722220),
 (0.864139354188464, -0.503252597154495, 1.32164171523800)]